[project]
name = "sql-mandelbrot-benchmark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datafusion>=50.1.0",
    "pyopencl>=2025.2.6",
]

[dependency-groups]
dev = [
    "ruff>=0.14.2",
]
